Repository hoa0217/happyhouse, pull requests merged in 2022-09, with the labels that each got.

#20 Front/18 세팅가져오기
  front/components/eventMarkerContainer.js
  front/components/showList.js
Labels: feature

#26 Front/24
  front/src/components/common/styles/common.module.scss
Labels: feature

#29 Front/18 리스트수정
  front/components/showList.js
Labels: refactoring

#34 [front]#2 custom Axios 추가
  front/next.config.js
  front/src/api/AddressStore.ts
  front/src/utils/axios.ts
Labels: setting

#39 [front] #18 매물상세페이지로이동
  front/src/api/HouseStore.ts
  front/src/components/kaKaoMap/mapMarker/index.tsx
  front/src/components/kaKaoMap/mapMarker/showList/index.tsx
  front/src/components/kaKaoMap/mapMarker/showList/show.tsx
  front/src/components/kaKaoMap/mapMarker/showList/showList.module.scss
  front/src/pages/index.tsx
  front/src/query/houseQuery.ts
Labels: feature

#41 [front] #18 파일수정
  front/src/components/kaKaoMap/KakaoMap.tsx
  front/src/components/kaKaoMap/KakaoMapWrapper.tsx
  front/src/components/kaKaoMap/index.tsx
  front/src/components/kaKaoMap/mapMarker/index.tsx
  front/src/components/kaKaoMap/mapMarker/showList/show.tsx
  front/src/components/kaKaoMap/select/index.tsx
  front/src/components/kaKaoMap/utils/moveMap.tsx
  front/src/pages/index.tsx
Labels: refactoring

#49 [front]#47 Loading 컴포넌트 css 추가
  front/styles/common.scss
  front/styles/reset.scss
Labels: feature

#50 Front/14
  front/next.config.js
  front/package-lock.json
  front/package.json
  front/src/api/HouseStore.ts
  front/src/components/detailPage/DetailHeader.tsx
  front/src/components/detailPage/HouseInfo/HousePriceInfo.tsx
  front/src/components/detailPage/HouseInfo/IntroduceHouse.tsx
  front/src/components/detailPage/HouseInfo/PriceChart.tsx
  front/src/components/detailPage/HouseInfo/RealDealList.tsx
  front/src/components/detailPage/HouseInfo/index.tsx
  front/src/components/detailPage/HouseInfo/useChartDataSet.ts
  front/src/components/detailPage/detailPage.module.scss
  front/src/components/detailPage/index.tsx
  front/src/domain/rs/house/detail/HouseDetailRs.ts
  front/src/pages/detail/[id].tsx
  front/src/pages/detail/villa/[id].tsx
  front/src/query/houseQuery.ts
  front/tsconfig.paths.json
Labels: feature

#51 Front/46 회원가입쿼리
  front/package-lock.json
  front/package.json
  front/src/api/HouseStore.ts
  front/src/api/JoinStore.ts
  front/src/api/LoginStore.ts
  front/src/api/index.ts
  front/src/components/common/layout/header/index.tsx
  front/src/components/common/loading/loading.module.scss
  front/src/components/kaKaoMap/KakaoMap.tsx
  front/src/components/kaKaoMap/KakaoMapWrapper.tsx
  front/src/components/kaKaoMap/index.tsx
  front/src/components/kaKaoMap/mapMarker/index.tsx
  front/src/components/kaKaoMap/mapMarker/showList/index.tsx
  front/src/components/signIn/index.tsx
  front/src/components/signIn/schema.ts
  front/src/components/signIn/signIn.module.scss
  front/src/components/signUp/index.tsx
  front/src/domain/rq/join/JoinRq.ts
  front/src/domain/rq/login/LoginRq.ts
  front/src/domain/rs/adress/SidoListRs.ts
  front/src/domain/rs/house/officetel/OfficeHouseListRs.ts
  front/src/domain/rs/house/officetel/OfficeMapListRs.ts
  front/src/domain/rs/join/JoinRs.ts
  front/src/domain/rs/login/LoginRs.ts
  front/src/domain/vo/house/officetel/OfficeHouseInfoListVO.ts
  front/src/domain/vo/house/officetel/OfficeMapListVO.ts
  front/src/pages/apart.tsx
  front/src/pages/index.tsx
  front/src/pages/join.tsx
  front/src/pages/login.tsx
  front/src/pages/officetel.tsx
  front/src/query/houseQuery.ts
  front/src/query/joinQuery.ts
  front/src/query/loginQuery.ts
  front/styles/reset.scss
Labels: feature
