Repository hoa0217/happyhouse, pull requests merged in 2022-08, with the labels that each got.

#5 Front/4
  front/pages/index.js
Labels: feature

#8 [front] #4 맵 컴포넌트 추가
  front/.gitignore
  front/components/select.js
  front/next.config.js
  front/package-lock.json
  front/package.json
  front/pages/_app.js
  front/pages/_document.js
  front/pages/index.js
Labels: feature

#9 [front] #4 맵 수정
  front/components/eventMarkerContainer.js
  front/components/select.js
  front/package-lock.json
  front/package.json
  front/pages/_app.js
  front/pages/index.js
Labels: refactoring

#19 front/4 지도이동수정
  front/components/eventMarkerContainer.js
Labels: refactoring

#22 [front]#21 babel, prettier, tsconfig, document 초기 세팅
  front/.babelrc
  front/.eslintrc.json
  front/.prettierignore
  front/.prettierrc
  front/next-env.d.ts
  front/package-lock.json
  front/package.json
  front/pages/_app.js
  front/pages/_document.js
  front/pages/index.js
  front/src/components/documents/KaKaoMap.tsx
  front/src/pages/_app.tsx
  front/src/pages/_document.tsx
  front/src/pages/api/hello.js
  front/src/pages/index.tsx
  front/src/pages/index2.js
  front/tsconfig.json
  front/tsconfig.paths.json
Labels: setting
