Repository hoa0217/happyhouse, pull requests merged in 2022-10, with the labels that each got.

#60 [front] #2 header css 수정
  front/public/img/header/iconLogo.png
  front/src/components/common/layout/header/header.module.scss
  front/src/components/common/layout/header/index.tsx
  front/styles/constants.scss
  front/styles/reset.scss
Labels: feature

#62 [front] #46 api변경
  front/next.config.js
  front/package-lock.json
  front/package.json
  front/public/img/kakaoMap/iconHome.png
  front/src/api/HouseStore.ts
  front/src/components/common/layout/index.tsx
  front/src/components/kaKaoMap/KakaoMap.tsx
  front/src/components/kaKaoMap/mapMarker/index.tsx
  front/src/components/kaKaoMap/mapMarker/showList/index.tsx
  front/src/components/kaKaoMap/mapMarker/showList/show.tsx
  front/src/components/kaKaoMap/mapMarker/showList/showList.module.scss
  front/src/components/kaKaoMap/select/index.tsx
  front/src/components/kaKaoMap/select/select.module.scss
  front/src/components/signIn/index.tsx
  front/src/components/signIn/schema.ts
  front/src/components/signIn/signIn.module.scss
  front/src/domain/rs/house/apt/HouseInfoListRs.ts
  front/src/domain/rs/house/apt/MapListRs.ts
  front/src/domain/vo/house/apt/HouseInfoListVO.ts
  front/src/domain/vo/house/apt/MapListVO.ts
  front/src/pages/_app.tsx
  front/src/query/loginQuery.ts
  front/src/store/index.ts
  front/src/store/reducer/loginReducer.ts
  front/tsconfig.paths.json
Labels: refactoring

#69 [front] #68 MyApp > SSR Setting
  front/src/pages/_app.tsx
Labels: feature

#71 Front/70
  front/src/api/HouseStore.ts
  front/src/api/VillaStore.ts
  front/src/api/index.ts
  front/src/components/detailPage/DetailHeader.tsx
  front/src/components/detailPage/HouseInfo/HousePriceInfo.tsx
  front/src/components/detailPage/HouseInfo/IntroduceHouse.tsx
  front/src/components/detailPage/HouseInfo/PriceChart.tsx
  front/src/components/detailPage/HouseInfo/RealDealList.tsx
  front/src/components/detailPage/HouseInfo/index.tsx
  front/src/components/detailPage/HouseInfo/useChartDataSet.ts
  front/src/components/detailPage/detailPage.module.scss
  front/src/components/detailPage/index.tsx
  front/src/domain/rs/house/detail/HouseDetailRs.ts
  front/src/domain/rs/house/detail/index.ts
  front/src/domain/rs/house/list/index.ts
  front/src/domain/rs/house/map/apt/index.ts
  front/src/domain/rs/house/map/officetel/index.ts
  front/src/domain/rs/types/index.ts
  front/src/domain/rs/villa/detail/index.ts
  front/src/domain/rs/villa/list/oneroom/index.ts
  front/src/domain/rs/villa/list/tworoom/index.ts
  front/src/domain/rs/villa/map/oneroom/index.ts
  front/src/domain/rs/villa/map/tworoom/index.ts
  front/src/pages/detail/[id].tsx
  front/src/pages/detail/house/apt/[id].tsx
  front/src/pages/detail/house/officetel/[id].tsx
  front/src/pages/detail/villa/[id].tsx
  front/src/pages/detail/villa/oneroom/[id].tsx
  front/src/pages/detail/villa/tworoom/[id].tsx
  front/src/query/VillaQuery.ts
  front/src/query/houseQuery.ts
Labels: feature

#76 [front] #46 로그인시헤더전환
  front/src/components/common/layout/header/header.module.scss
  front/src/components/common/layout/header/index.tsx
  front/src/components/signIn/signIn.module.scss
  front/src/pages/bucket.tsx
  front/src/pages/mypage.tsx
Labels: refactoring

#80 [front] #77 필요없는 폴더삭제
  front/components/showList.js
Labels: delete
